# Generated by Django 3.2.5 on 2021-07-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='Name',
        ),
    ]
